name: cutruntools2.1
dependencies:
- python=3.6
- cmake>=3.16
- openjdk=17.0.3
- bioconda::bowtie2
- bioconda::samtools
- bioinfo:macs2
- bioconda::bedops
- bioconda::bedtools
- bioconda::deeptools
- conda-forge::parallel
- bioconda::tabix
- pip
- pip:
  - umap-learn
  - leidenalg
  - igraph
